[package]
name = "Typing-Tutor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.188", features = ["derive"]}
serde_json = "1.0"
nannou = "0.18.1"
rand = "0.8.5"